spring:
  profiles:
    include:
      - domain
      - data
      - client

  main:
    web-application-type: none

resilience4j:
  circuitbreaker:
    instances:
      DiscordNotification-send:
        sliding-window-size: 3
        minimum-number-of-calls: 2
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 50
        slow-call-duration-threshold: 5s
        slow-call-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
