services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  localstack:
    image: localstack/localstack:2.2.0
    container_name: localstack
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - EAGER_SERVICE_LOADING=1
      - PERSISTENCE=1
      - PERSIST_ALL=false
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./init/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
